/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MenuCategory = IDL.Record({
  'id' : IDL.Text,
  'outletId' : IDL.Text,
  'name' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'outletId' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Outlet = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Customer = IDL.Record({ 'name' : IDL.Text, 'mobile' : IDL.Text });
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'menuItemId' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'total' : IDL.Float64,
  'createdAt' : IDL.Int,
  'customerMobile' : IDL.Text,
  'outletId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'taxAmount' : IDL.Float64,
  'subtotal' : IDL.Float64,
  'taxApplied' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMenuCategory' : IDL.Func([IDL.Text, IDL.Text], [MenuCategory], []),
  'createMenuItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool], [MenuItem], []),
  'createOutlet' : IDL.Func([IDL.Text, IDL.Bool], [Outlet], []),
  'deleteMenuCategory' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteMenuItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteOrder' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteOutlet' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getMenuCategories' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(MenuCategory)], ['query']),
  'getMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(MenuItem)], ['query']),
  'getMenuItems' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(MenuItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([IDL.Opt(IDL.Int), IDL.Opt(IDL.Int), IDL.Opt(IDL.Text)], [IDL.Vec(Order)], ['query']),
  'getOutlet' : IDL.Func([IDL.Text], [IDL.Opt(Outlet)], ['query']),
  'getOutlets' : IDL.Func([], [IDL.Vec(Outlet)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Float64, IDL.Bool, IDL.Float64, IDL.Float64, IDL.Text, IDL.Int], [Order], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMenuCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Opt(MenuCategory)], []),
  'updateMenuItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool], [IDL.Opt(MenuItem)], []),
  'updateOutlet' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Opt(Outlet)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MenuCategory = IDL.Record({
    'id' : IDL.Text,
    'outletId' : IDL.Text,
    'name' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'outletId' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Outlet = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Customer = IDL.Record({ 'name' : IDL.Text, 'mobile' : IDL.Text });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'menuItemId' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'total' : IDL.Float64,
    'createdAt' : IDL.Int,
    'customerMobile' : IDL.Text,
    'outletId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'taxAmount' : IDL.Float64,
    'subtotal' : IDL.Float64,
    'taxApplied' : IDL.Bool,
  });
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMenuCategory' : IDL.Func([IDL.Text, IDL.Text], [MenuCategory], []),
    'createMenuItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool], [MenuItem], []),
    'createOutlet' : IDL.Func([IDL.Text, IDL.Bool], [Outlet], []),
    'deleteMenuCategory' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteMenuItem' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteOrder' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteOutlet' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getMenuCategories' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(MenuCategory)], ['query']),
    'getMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(MenuItem)], ['query']),
    'getMenuItems' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(MenuItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([IDL.Opt(IDL.Int), IDL.Opt(IDL.Int), IDL.Opt(IDL.Text)], [IDL.Vec(Order)], ['query']),
    'getOutlet' : IDL.Func([IDL.Text], [IDL.Opt(Outlet)], ['query']),
    'getOutlets' : IDL.Func([], [IDL.Vec(Outlet)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Float64, IDL.Bool, IDL.Float64, IDL.Float64, IDL.Text, IDL.Int], [Order], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMenuCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Opt(MenuCategory)], []),
    'updateMenuItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool], [IDL.Opt(MenuItem)], []),
    'updateOutlet' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Opt(Outlet)], []),
  });
};

export const init = ({ IDL }) => { return []; };
