/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer { 'name' : string, 'mobile' : string }
export interface MenuCategory { 'id' : string, 'outletId' : string, 'name' : string }
export interface MenuItem {
  'id' : string,
  'name' : string,
  'available' : boolean,
  'outletId' : string,
  'category' : string,
  'price' : number,
}
export interface Order {
  'id' : string,
  'status' : string,
  'total' : number,
  'createdAt' : bigint,
  'customerMobile' : string,
  'outletId' : string,
  'items' : Array<OrderItem>,
  'taxAmount' : number,
  'subtotal' : number,
  'taxApplied' : boolean,
}
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'unitPrice' : number,
  'menuItemId' : string,
}
export interface Outlet { 'id' : string, 'active' : boolean, 'name' : string }
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'createMenuCategory' : ActorMethod<[string, string], MenuCategory>,
  'createMenuItem' : ActorMethod<[string, string, string, number, boolean], MenuItem>,
  'createOutlet' : ActorMethod<[string, boolean], Outlet>,
  'deleteCustomer' : ActorMethod<[string], boolean>,
  'deleteMenuCategory' : ActorMethod<[string], boolean>,
  'deleteMenuItem' : ActorMethod<[string], boolean>,
  'deleteOrder' : ActorMethod<[string], boolean>,
  'deleteOutlet' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], [] | [Customer]>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getMenuCategories' : ActorMethod<[[] | [string]], Array<MenuCategory>>,
  'getMenuItem' : ActorMethod<[string], [] | [MenuItem]>,
  'getMenuItems' : ActorMethod<[[] | [string]], Array<MenuItem>>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrders' : ActorMethod<[[] | [bigint], [] | [bigint], [] | [string]], Array<Order>>,
  'getOutlet' : ActorMethod<[string], [] | [Outlet]>,
  'getOutlets' : ActorMethod<[], Array<Outlet>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, string, string, Array<OrderItem>, number, boolean, number, number, string, bigint], Order>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMenuCategory' : ActorMethod<[string, string, string], [] | [MenuCategory]>,
  'updateMenuItem' : ActorMethod<[string, string, string, string, number, boolean], [] | [MenuItem]>,
  'updateOutlet' : ActorMethod<[string, string, boolean], [] | [Outlet]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
